### ISSUE TITLE
Revamp Boolean Operations

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#761]
Despite all the recent improvements on boolean operations in the https://github.com/paperjs/paper.js/tree/boolean-fix branch, built on top of @iconexperience's code that checks for curve overlaps, I start to agree with @hkrish in his observation that the current approach is too complex to fix for all failing edge cases:

- The code doesn't handle self-intersection in the source paths.
- The code that calculates winding contributions per segment seems to struggle once the shapes go below a certain size (see https://github.com/paperjs/paper.js/issues/648#issuecomment-134523915, to be confirmed in more testing)

@hkrish and @kuribas seem to think that using a sweep-line based algorithm for beziers is the way to go: 

https://github.com/paperjs/paper.js/issues/371#issuecomment-59428147
https://github.com/paperjs/paper.js/issues/371#issuecomment-59485104

I have found an open-source implementation in Objective C that I believe is based on sweep-line, outlined here:
http://losingfight.com/blog/2011/07/09/how-to-implement-boolean-operations-on-bezier-paths-part-3/

These two posts lead up to that final post:
http://losingfight.com/blog/2011/07/07/how-to-implement-boolean-operations-on-bezier-paths-part-1/
http://losingfight.com/blog/2011/07/08/how-to-implement-boolean-operations-on-bezier-paths-part-2/

The code lives here:
https://bitbucket.org/andyfinnell/vectorboolean/

And in 2014, @BohemianCoding sponsored him to improve the algorithm for inclusion in Sketch app:
http://losingfight.com/blog/2014/01/24/fixes-and-performance-enhancements-for-vectorboolean/

We could attempt porting this to JavaScript? But first we should perform some tests with the complex shapes that our current implementation chokes on, directly in the Objective C code base.

**Comment by kuribas** [comment]
@lehni I test for overlap before the bezier clip algorithm, because it would return an infinite (or very large) amount of points.  The source path is first split into curves that increase in the x direction, so there can be no self overlap.  The winding contribution is based on the direction of that segment.
A sweep line algorithm still has to take care of all these issues, but the advantage is that it needs to do less intersection tests for a typical drawing,  `O(log(n+m)(n+m))` versus `O(n²)`, where `m` is the number of intersections.
I am very much interested in the edge cases where your code chokes on, or also difficult cases that it does correctly.

**Comment by lehni** [comment]
@kuribas we do exactly the same, see here: 

https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1488

The edge cases turned out to be a bug in the code that sorted the found intersections before merging duplicates, and due to variations in precision, the sequence of the time parameters wasn't always the same (tiny variations lead to a different sequence of the found intersections). That's all fixed now!

And I start feeling much more confident in the current solution again. The only part missing now is handling self-intersecting source paths, and more testing... But what you say about the performance still holds, I am sure. Still better to have a working implementation than none : )

**Comment by iconexperience** [comment]
@lehni 

While I understand the algorithms for finding intersections quite well, I am still trying to get into the boolean operations algorithm. Are there any resources/papers that describe the used algorithm? There is of course the Vatti algorithm, and I found this resource:

http://davis.wpi.edu/~matt/courses/clipping/

Do you have any other links?

Regarding performance: I have already seen a bunch of potential improvements in the code, so I wouldn't worry too much. Let's make it work first.

**Comment by kuribas** [comment]
I have documented sweep line implementation: http://kuribas.hcoop.net/Overlap.html

**Comment by kuribas** [comment]
For clarity: this is another boolean operations algorithm than the one implemented in paperjs.

**Comment by iconexperience** [comment]
@kuribas This is great, but I think Jürg is correct, we should first try to make the current algorithm work, because it already works pretty well in the implementation is more or less finished. The big question is: Will is be possible to resolve the remaining cases where the current implementations still fails or are we on a dead end?

**Comment by lehni** [comment]
@iconexperience The algorithm that @hkrish fleshed out in 2013 is based on this video here about Path Operations by Google Chrome engineer Cary Clark who is working on Skia:
https://www.youtube.com/watch?v=OmfliNQsk88

@kuribas that's really great, thanks for putting it online! It sounds quite a bit smarter than what we're doing currently. I don't think I have the skills to port this over to JS though, unfortunately, having never written a single line of Haskell so far.

**Comment by lehni** [comment]
PS: I find it interesting that in order to find intersections, Cary suggests approximating cubics with multiple quadratics, solving their intersections mathematically and then going back to the cubics from there.

**Comment by iconexperience** [comment]
@lehni Just for the record, replacing cubic beziers with quadratic ones is what all tools that convert svgs to fonts have to do, because TrueType only supports quadratic bezier curves. So in case we need code for doing this, we could take a look at <a href="https://github.com/fontello">Fontello</a> or similar projects.

**Comment by lehni** [comment]
@iconexperience yes I'm aware of that. I'm quite happy with our fat line clipping code currently though...

**Comment by iconexperience** [comment]
@lehni I agree, finding intersections has become pretty good recently.

I watched the video and luckily the algorithm does not seem to be very difficult. It would be nice to have the canvs he uses for PaperJS. Let's see if I can produce something that will help with debugging.

**Comment by kuribas** [comment]
I watched the whole video.  At 19:40 he states that it is hard to solve a cubic using math.  However Sederberg and Nishita have shown that it is possible using [implicitization](http://technion.ac.il/~ihanniel/036067/seminar_papers/Sederberg_nishita_bezclip.pdf).  According to the paper this method is faster than the bezier clip algorithm.  It reduces to a maximum 9th degree polynomial equation, which can be solved numerically.  For example using [Polynomial Real Root Finding in Bernstein Form](http://ir.nmu.org.ua/bitstream/handle/123456789/111417/40ffff39f2dd54b3467a4431e412d181.pdf?sequence=1)

**Comment by kuribas** [comment]
It seems he wasn't aware of this research, or his method predates it.

**Comment by lehni** [comment]
@kuribas neither was I : ) What did you think of his approach otherwise? How does it compare to what you are doing?

**Comment by kuribas** [comment]
@lehni I linked to the wrong paper, implicitization is explained in (cagd)[http://tom.cs.byu.edu/~557/text/cagd.pdf].  I am using bezier clipping like you do.  According to the paper imlicitization is the fastest method for curves of degree 2 and 3, so I assume it will be faster than approximating a quadratic bezier, but I haven't tested it.

The algorithm in the video does O(n*n) comparisons, while my one does O((n+m)log(n+m)) comparisons (n = number of segments, m = number of intersections).  For a large number of segments, this may give a significant performance improvement.   For a few segments I don't know, that would need to be tested.

I actually look at all points, since that is necessary for the sweepline algorithm to test intersections.  For the rest both methods seem to be the very similar.  I actually test if two curves are overlapping, or if a point comes near a curve.

**Comment by nicholaswmin** [comment]
So, hate to be late to the party but my 2 cents is this:

Has anyone thought about: 

- Flattening the paths 
- Using a *polygon-clipping* algorithm 
- Reconstructing the curves

Some info about the curves was kept before flattening that would help on the accuracy of reconstructing them back after clipping has been done. 

AFAIK, this was discussed at a point in Angus Johnson's Clipper Lib, somewhere here: http://sourceforge.net/p/polyclipping/discussion/1148419/thread/cae35ac2/?limit=25&page=2

**Comment by kuribas** [comment]
@nicholaswmin according to sederbergh recursive subdivision is much slower than implicitisation.  He gives the following relative speed for cubic beziers:

ex1: clipping 2.5, implicitisation 1, subdivision 15

ex2: clipping 1.8, implicitisation 1, subdivison 6

**Comment by lehni** [comment]
@nicholaswmin I've heard this suggestion before but your link is the first time I see it described in detail.

We've gone very far down the current road which works very well for a whole lot of cases (on the `boolean-fix` branch). The remaining edge-cases and the handling of self-intersection is what's left to fix, and there are plans in place for both. We should be good to go quite soon!

Ideally I'd like to see @kuribas approach based on the sweepline algorithm implemented in paper.js, but that's another project... I'm already happy when we can finally say that our current implementation is robust, which it almost is now : )

**Comment by nicholaswmin** [comment]
@lehni True - also I doubt the approach I described is faster than what you already have in place anyway.

**Comment by lehni** [comment]
@nicholaswmin it looks like we just finally managed to resolve all known issues with boolean operations, except this one rare edge case (#773) It now even supports operations on self-intersecting paths! What's left to do is more testing and some optimizations. This was a very long time in the making, very exciting news!

**Comment by petrbrzek** [comment]
Btw: Someone ported Andy Finnell's VectorBoolean to Swift (https://github.com/lrtitze/Swift-VectorBoolean). So it could be a little bit easier to port it to JS.

**Comment by lehni** [comment]
@petrbrzek thanks for pointing that out! But in the meantime we've made so much progress on the current implementation that I don't think we require a port anymore. Our implementation also works with a whole lot less code, which is welcome in a browser environment.

But it's always good to compare edge cases. Did you already compile it? If so, could you compare and see how it handles cases where paths only touch or overlap along curves / lines? e.g. #450 and #449?

**Comment by iconexperience** [comment]
The recent improvements on the boolean operations are quite impressive, but whenever a change to the code was made, we could see the effect of the change on some cases, but we had no way to quantize the effect of the change regarding the quality of the boolean operations.

Therefore I wrote a test case based on <a href="http://embed.plnkr.co/jkNGoe8fD0li9DmY7u76/">my first curve offset approach</a>, which takes a curve, splits it into several subcurves, creates an offest path for reach subcurve, and finally merges the offset path using boolean operations. The test automatically runs through 8000 curves, making about 42000 calls to `path.unite()`. The curves are fairly random, but each time the same curves are used. Since the algorithm creating the offset paths is rather clumsy, there are many cases with small hooks, self intersections, tiny loops and many imprecisions, it is very useful for creating difficult test cases for finding hidden issues in the boolean operations. I ran this test for the most recent commits and recorded the number of glitches (error messages still creating a result) and errors (usually stack size exceeded errors). I also compared to the result before the commit to find the number of new and resolved cases. And here are the results:

Commit | glitches absolute | glitches relative | errors absolute | errors relative | comment
---|---|---|---|---|---------
<a href="https://github.com/paperjs/paper.js/commit/9b883e5fb6e3a39df2dbd1ef097277c6ea089e1b">9b883e5</a> | 43 | +0/-0 | 0 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/5601e219969f5b085442a9ee57b2d85624cb13e0">5601e2</a> | 43 | +0/-0 | 0 | +0/0
<a href="https://github.com/paperjs/paper.js/commit/80731830107929d441768673ec5693a1a8414c6b">807318</a> | 43 | +2/-0 | 0 | +0/-1 | includes 5601e21
<a href="https://github.com/paperjs/paper.js/commit/79cb21668435908579c24bb41cffa9fc5a4a04fb5">79cb21</a> |  |  |  | | unusable, skipped
<a href="https://github.com/paperjs/paper.js/commit/86b1b74869e61ce8484e6a7b844ea62406b623e5">86b1b74</a> | 41 | +2/-2 | 1 | +1/-3 | includes 5601e21
<a href="https://github.com/paperjs/paper.js/commit/2bed61164819aca70fd0458cc31c48f638d40da0">2bed611</a> | 41 | +0/-0 | 3 | +0/-0 | includes <a href="https://github.com/paperjs/paper.js/commit/5601e219969f5b085442a9ee57b2d85624cb13e0">5601e2</a>
<a href="https://github.com/paperjs/paper.js/commit/6fb4b7e3c40c05186592af4b37b25d019842fbe1">6fb4b7e</a> | 41 | +0/-5 | 3 | +0/-0 | includes 5601e21
<a href="https://github.com/paperjs/paper.js/commit/5d7a5960266797dc3fa6e1a393aa2555e17c6dcf">5d7a596</a> | 46 | +0/-0 | 3 | +0/-0 | includes 5601e21
<a href="https://github.com/paperjs/paper.js/commit/50c74733379d67e52b404aabcee11862ef2eea30">50c7473</a> | 46 | +1/-15 | 3 | +1/-1 | includes 5601e21
<a href="https://github.com/paperjs/paper.js/commit/2167e458ae646f1131bc419e1f8f008dfad5faa9">2167e45</a> | 60 | +0/-0 | 3 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/7496a7c9e25788fe0da91e9ab171f86ef74ae6e6">7496a7c</a> | 60 | +0/-0 | 3 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/632eb25f19fbbe5b1aeb607b1badab181a5bdbb8">632eb25</a> | 60 | +0/-2 | 3 | +1/-0
<a href="https://github.com/paperjs/paper.js/commit/c6de2f7f231ef5b9fbada4c372586e2fa6b99ce0">c6de2f7</a> | 62 | +0/-0 | 2 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/11611c8fe2aa2001661c4ed43105d94c15905c7d">11611c8</a> | 62 | +1/-0 | 2 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/a808aaf0fa0b4f7809b33f40544f8c31b1645f34">a808aaf</a> | 61 | +0/-0 | 2 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/de57a7fbc8891561c5435b4433f6fafc8bce1ccf">de57a7f</a> | 61 | +0/-0 | 2 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/c0bb6890bde71837bdefbdb77d62b7bc5cfdbf01">c0bb689</a> | 61 | +0/-0 | 2 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/4b4ccbac09707c6b93cbb2c4fecf4a488a3df9bc">4b4ccba</a> | 61 | +21/-5 | 2 | +2/-0
<a href="https://github.com/paperjs/paper.js/commit/9b883e5fb6e3a39df2dbd1ef097277c6ea089e1b">9b883e5</a> | 45 | +3/-0 | 0 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/b8c6eb46ade2560f34b5c44525b8f46861b5b85e">b8c6eb4</a> | 42 | +1/-0 | 0 | +0/-0 | includes 72f9705
<a href="https://github.com/paperjs/paper.js/commit/c77165be3ac5d564506eec66cc67480cb80be1f0">c77165b</a> | 41 | +1/-27 | 0 | +0/-0 | includes 72f9705
<a href="https://github.com/paperjs/paper.js/commit/75a004187e8f5db43236f08ed63d7b3492b87257">75a0041</a> | 67 | +3/-0 | 0 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/5f706a4a5d1e36509a1e80776527e30449584c84">5f706a4</a> | 64 | +1/-12 | 0 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/9bcf369e6a153dc19aac145a0089c0a4fec3e949">9bcf369</a> | 75 | +0/-0 | 0 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/2a7d1c5728d1c80cb2c1818308e47f9bacaf057b">2a7d1c5</a> | 75 | +0/-6 | 0 | +0/-11
<a href="https://github.com/paperjs/paper.js/commit/4e9bac1ca5de00142edb1193ee45eab8d04edf8f">4e9bac1</a> | 81 | +0/-0 | 11 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/ec70fa1806c41d19f04db83962aadbe789c7f934">ec70fa1</a> | 81 | +8/-98 | 11 | +4/-2
<a href="https://github.com/paperjs/paper.js/commit/3fa810a5579602a46e6656890aacd8cec7bf8e9c">3fa810a</a> | 171 | +0/-0 | 9 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/fd927cbe2235d328862a56cec0fdce9b2933786d">fd927cb</a> | 171 | +3/-0 | 9 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/fc0b5a8858e3e26ca4c6529327fd72a8358ffbf0">fc0b5a8</a> | 168 | +0/-2 | 9 | +0/-4
<a href="https://github.com/paperjs/paper.js/commit/c79166a46fb6926a0d7a3b204afe4b0d6f0b7def">c79166a</a> | 170 | +0/-2 | 13 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/cf5bf38c3b471c8e299a22d66b0a52199fa8cebb">cf5bf3</a> | 172 | +0/-0 | 13 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/515d4ff93d99f5b0e3e0951d2a57968a47987320">515d4f</a> | 172 | +9/-11 | 13 | +3/-1
<a href="https://github.com/paperjs/paper.js/commit/cc7e60e51aec72ea79fee8cb3a995d5daa5fdde4">cc7e60e</a> | 174 | +2/-0 | 11 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/20f950ac65dfb0f28bdc467bf31742e240fefa1e">20f950a</a> | 172 | +0/-0 | 11 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/db1ecdddd589a46a8a3c58ee1b303ea6bacbfade">db1ecdd</a> | 172 | +6/-2 | 11 | +1/-0
<a href="https://github.com/paperjs/paper.js/commit/6a29f200e3360ff37d3fcff906c1c218894523ad">6a29f20</a> | 168 | +0/-1 | 10 | +0/-2
<a href="https://github.com/paperjs/paper.js/commit/51c34444db937b90a5dced1f3d8b481afc38e5ae">51c3444</a> | 169 | +0/-0 | 12 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/84bcc537e1ee8838d3bbda360b43120320890a59">84bcc53</a> | 169 | +6/-7 | 12 | +3/-6
<a href="https://github.com/paperjs/paper.js/commit/0f61ce896a6a52fd106df6a725a4f8afa52ddaa7">0f61ce8</a> | 170 | +0/-0 | 15 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/812ac63e60ae8c19607a0080295896bf44902a1a">812ac63</a> | 170 | +14/-44 | 15 | +1/-3
<a href="https://github.com/paperjs/paper.js/commit/812ac63e60ae8c19607a0080295896bf44902a1a">812ac63</a> | 209 | +9/-0 | 17 | +16/-0
<a href="https://github.com/paperjs/paper.js/commit/e36319b71a15b51826c8e669279b7a56db997672">e36319b</a> | 200 | +6/-1 | 1 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/f6f42fe09b7995450b1694494cf65b5a79203467">f6f42fe</a> | 195 | +0/-2048 | 1 | +0/-6
<a href="https://github.com/paperjs/paper.js/commit/19a17b29187c11950e63711deabff34284100b6e">19a17b2</a> | 2243 | +0/-0 | 7 | +0/-0
<a href="https://github.com/paperjs/paper.js/commit/1ad95c9020e2381dc2df831621c12faf8abaae8a">1ad95c9</a> | 2243 | +2243/-0 | 7 | +7/-0

You should note that the results are not very representative, but the give an indication of the effectiveness of each commit. I hope this is helpful.

I will make this test available here, but please be patient, as it need some cleaning first.

**Comment by lehni** [comment]
This is very useful, thanks! It'd be great if you could share the code for this with me, so I can immediately see the impact of my changes on the result.

**Comment by iconexperience** [comment]
I will, but I need to clean it first, because it's a mess. I will post more examples if you do not mind?

**Comment by lehni** [comment]
Sure keep sending them : ) I'm curious about the +1 in 80731830107929d441768673ec5693a1a8414c6b... That doesnt' really make sense, so I'd like to play with it to understand what happened : )

**Comment by lehni** [comment]
So after a ton of more work, the current implementation works with all known edge cases from @iconexperience's test suite. It's been a long and bumpy road to get here, but the code is now very sturdy and clean.I'm super happy with how it all turned out. I am closing this issue now, as all that's left to do is implement some unit tests to protect against regressions, and roll it all out.

**Comment by be5invis** [comment]
@lehni is it possible to create a separate library which deals with boolean operations only, since paper is a bit too large.

**Comment by lehni** [comment]
@be5invis too large for what? And without paper.js, on what kind of data-structures would it operate on? SVG? Many things are possible, but I don't have the urge work on this particular project. The boolean code relies heavily on many of the data structures in paper.js, which is one of the reasons for the library was to be built this way. I'm happy with that structure, and don't think that a 180kb library is too heavy for handling the complex math involved with such bezier curve operations. Having to maintain two separate libraries that do the same thing on the other hand would be too heavy in a whole different way.

**Comment by petrbrzek** [comment]
@lehni: Nice job man! :+1:

**Comment by petrbrzek** [comment]
@lehni When you plan to release a new version?
